pipeline {
    agent any

    stages {
		stage("threat modeling") {
			agent {
				docker {
					image "rusakovichma/tic-taac:latest"
					args '''\
						--user 0 \
						--volume ${WORKSPACE}/threat-model:/threat-model:ro \
						--volume ${WORKSPACE}/report:/report:rw \
						--entrypoint ""
					'''
					reuseNode true 
				}
			}
			steps {
				 script {
					 def result = sh label: "tic-taac", returnStatus: true,
						 script: """\
							mkdir -p report &>/dev/null
							/usr/share/tic-taac/bin/tic-taac.sh \
							--failOnThreatRisk High \
							--threatModel /threat-model/threat-model.yml \
							--mitigations /threat-model/whitelisting.yml \
							--outFormat html \
							--out /report
						 """
					 if (result > 0) {
						  unstable(message: "Unmitigated Threats found")
					 } 
				 }
			}
		}
	}
}
